import Foundation

enum FeatureLocalizations {
    static let fallback: [String: String] = [
        "annotation.tool.ruler": "标尺与参考线",
        "feature.tools.title": "截图工具",
        "feature.tools.open": "打开图片",
        "feature.tools.paste": "粘贴图片",
        "feature.tools.choose": "先选择一张图片",
        "feature.tools.chooseHelp": "从文件或剪贴板打开图片，也可以从截图历史的更多菜单进入。",
        "feature.draft.edit": "继续编辑",
        "feature.draft.keep": "保留可编辑原稿",
        "feature.draft.setting": "在历史中保留可编辑原稿",
        "feature.draft.privacy": "原稿随历史一起清理。含马赛克或脱敏区域时会固化整张图，不保留遮盖前的内容；裁剪、旋转也会固化已有标注。关闭历史或命中排除应用时不保存原稿。",
        "feature.ruler.units": "测量单位；导入图片的点值取决于图片尺寸信息",
        "feature.ruler.modes": "拖动绘制距离或贯穿图片的参考线",
        "feature.ruler.unit.pixels": "像素 px",
        "feature.ruler.unit.points": "点 pt",
        "feature.ruler.mode.distance": "测量距离",
        "feature.ruler.mode.horizontal": "水平参考线",
        "feature.ruler.mode.vertical": "垂直参考线",
        "feature.long.title": "长图处理",
        "feature.long.help": "在图片上纵向拖动，选中要删除的中段；也可输入从顶部开始的像素行。删除可撤销，分页从上到下连续输出。",
        "feature.long.from": "起始行",
        "feature.long.to": "结束行",
        "feature.long.remove": "删除中段",
        "feature.long.pageHeight": "每页高度",
        "feature.long.exportPages": "导出分页 PNG",
        "feature.long.use": "复制并存入历史",
        "feature.ocr.title": "结构化 OCR",
        "feature.ocr.format": "复制格式",
        "feature.ocr.format.plain": "纯文本",
        "feature.ocr.format.layout": "保留布局",
        "feature.ocr.format.tsv": "表格 TSV",
        "feature.ocr.format.markdown": "Markdown 表格",
        "feature.ocr.help": "使用本机识别，可直接修改预览后复制。表格列由文字位置推断，请核对空单元格和合并单元格；Markdown 默认首行为表头。重新识别会替换预览中的修改。",
        "feature.ocr.recognize": "重新识别",
        "feature.ocr.empty": "没有识别到文字。",
        "feature.guide.title": "步骤文档",
        "feature.guide.untitled": "操作步骤",
        "feature.guide.documentTitle": "文档标题",
        "feature.guide.stepTitle": "步骤标题",
        "feature.guide.step": "步骤 %d",
        "feature.guide.help": "主动截图并填写操作或问题说明，可调整顺序。最多 100 步；文档不会自动落盘，请保存原稿以便下次继续。关闭窗口会暂停收集，已收集步骤保留到退出应用。",
        "feature.guide.collect": "收集后续截图",
        "feature.guide.capture": "截图添加一步",
        "feature.guide.addCurrent": "添加当前图片",
        "feature.guide.count": "%d / 100 步",
        "feature.guide.up": "上移",
        "feature.guide.down": "下移",
        "feature.guide.remove": "删除此步骤",
        "feature.guide.empty": "截图或添加图片以开始记录",
        "feature.guide.new": "新建",
        "feature.guide.open": "打开原稿",
        "feature.guide.save": "保存原稿",
        "feature.guide.unsaved": "原稿有未保存更改",
        "feature.guide.discardTitle": "放弃当前未保存的文档？",
        "feature.guide.discardHelp": "先取消并保存原稿，可以保留图片和说明以便继续编辑。",
        "feature.guide.discard": "放弃更改",
        "feature.export.pdf": "导出 PDF",
        "feature.export.markdown": "导出 Markdown + 图片",
        "feature.export.chooseFolder": "导出到此文件夹",
        "feature.record.start": "区域短录屏",
        "feature.record.title": "短录屏 · 无声 MP4",
        "feature.record.status": "录制 %d / 60 秒 · 无声",
        "feature.record.stop": "停止并预览",
        "feature.record.preview": "预览与裁剪录屏",
        "feature.record.trimHelp": "选择开始和结束时间（秒），预览后保存。关闭窗口会丢弃未保存视频。输出为无声 H.264 MP4，最长 60 秒，画面不超过 1920 × 1080。",
        "feature.record.trimStart": "开始",
        "feature.record.trimEnd": "结束",
        "feature.record.playTrim": "预览选定片段",
        "feature.record.save": "保存 MP4",
        "feature.record.saved": "视频已保存。",
        "feature.quit.title": "仍有未保存的步骤文档或视频",
        "feature.quit.help": "取消退出可继续保存；继续退出会丢弃未保存内容并停止录屏。",
        "feature.quit.discard": "丢弃并退出",
        "feature.error.title": "无法完成操作",
        "feature.error.invalidDocument": "文档、图片或参数无效，请检查后重试。",
        "feature.error.imageTooLarge": "内容超过处理上限，请缩小图片、减少步骤或增大分页高度。",
        "feature.error.emptyDocument": "请先添加图片或步骤。",
        "feature.error.recordingFailed": "无法完成录屏，请检查屏幕录制权限和可用磁盘空间。",
        "feature.error.noVideoFrames": "没有收到可用画面，请保持录制区域可见后重试。",
        "feature.record.discardTitle": "丢弃未保存的录屏并开始新录制？",
        "feature.record.discardHelp": "取消后可在预览窗口保存当前视频。",
        "feature.record.exporting": "视频正在保存，请完成后再退出。",
    ]
}
