import Foundation

enum AppLanguage: String, CaseIterable, Identifiable, Sendable {
    case system
    case simplifiedChinese = "zh-Hans"
    case traditionalChinese = "zh-Hant"
    case english = "en"

    static let userDefaultsKey = "appLanguage"
    var id: String { rawValue }

    var title: String {
        switch self {
        case .system: L10n.text("language.system")
        case .simplifiedChinese: "简体中文"
        case .traditionalChinese: "繁體中文"
        case .english: "English"
        }
    }

    var bundleCode: String? {
        switch self {
        case .system: nil
        default: rawValue
        }
    }

    static func current(defaults: UserDefaults = .standard) -> AppLanguage {
        guard let value = defaults.string(forKey: userDefaultsKey),
              let language = AppLanguage(rawValue: value) else { return .system }
        return language
    }
}

enum L10n {
    static func text(_ key: String, _ arguments: CVarArg...) -> String {
        let format = localizedString(for: key)
        guard !arguments.isEmpty else { return format }
        return String(format: format, locale: locale, arguments: arguments)
    }

    static var locale: Locale {
        let selected = AppLanguage.current()
        if let code = selected.bundleCode { return Locale(identifier: code) }
        return .autoupdatingCurrent
    }

    private static func localizedString(for key: String) -> String {
        let selected = AppLanguage.current()
        if let code = selected.bundleCode,
           let path = Bundle.main.path(forResource: code, ofType: "lproj"),
           let bundle = Bundle(path: path) {
            return bundle.localizedString(forKey: key, value: fallback[key] ?? key, table: nil)
        }
        return Bundle.main.localizedString(forKey: key, value: fallback[key] ?? key, table: nil)
    }

    // 单元测试和 SwiftPM 运行环境没有 .app 本地化资源时仍提供可读的简体中文。
    private static let fallback: [String: String] = [
        "language.system": "跟随系统",
        "action.region": "区域截图",
        "action.delayedRegion": "3 秒延迟",
        "action.repeatRegion": "重复上次区域",
        "action.filePin": "导入图片贴屏",
        "fileImport.panelMessage": "选择一张或多张图片贴到屏幕。",
        "action.scrollingRegion": "滚动截图",
        "action.display": "当前屏幕截图",
        "action.window": "光标所在窗口截图",
        "action.regionAndPin": "区域截图并贴屏",
        "action.clipboardPin": "粘贴剪贴板图片",
        "action.togglePins": "显示或隐藏全部贴图",
        "quickOverlay.title": "截图已就绪",
        "quickOverlay.annotate": "标注",
        "quickOverlay.dragHelp": "拖到其他应用",
        "quickOverlay.preview": "最近截图预览",
        "preferences.quickCaptureOverlay": "显示截图后快速操作",
        "preferences.quickCaptureOverlayHelp": "截图完成后短暂显示预览，可复制、保存、标注、贴屏或拖到其他应用。",
        "preferences.historyEnabled": "保存截图历史",
        "preferences.historyMaximumItems": "最多保留",
        "preferences.historyRetention": "保留时间",
        "preferences.historyRetention.forever": "不限时间",
        "preferences.historyRetention.oneDay": "1 天",
        "preferences.historyRetention.sevenDays": "7 天",
        "preferences.historyRetention.thirtyDays": "30 天",
        "preferences.historyRetention.ninetyDays": "90 天",
        "preferences.historyOCRIndexing": "本机 OCR 搜索",
        "preferences.historySearch": "搜索识别文字或尺寸",
        "preferences.deleteHistoryItem": "删除这张截图",
        "preferences.deleteHistoryItemFailed": "无法删除截图：%@",
        "preferences.historyPolicyFailed": "无法应用历史保留策略：%@",
        "common.save": "保存",
        "common.close": "关闭",
        "common.enabled": "已开启",
        "common.disabled": "已关闭",
        "overlay.selectionWidth": "选区宽度",
        "overlay.selectionHeight": "选区高度",
        "overlay.lockAspectRatio": "锁定宽高比",
        "overlay.editSelectionSize": "输入选区尺寸",
        "overlay.editSelectionSizeHelp": "从选区中心调整尺寸。选择比例后，宽度、高度、方向键和拖动控制点都会保持该比例。",
        "overlay.invalidSelectionSize": "请输入大于 0 的数字宽度和高度。",
        "overlay.aspectRatio": "宽高比",
        "overlay.aspectHelp": "选择“自由”可独立输入宽高；其他选项会实时联动，并自动缩小到屏幕范围内。",
        "overlay.aspect.free": "自由",
        "overlay.aspect.current": "当前",
        "overlay.aspect.currentValue": "当前 %@",
        "overlay.aspect.square": "1:1",
        "overlay.aspect.fourThree": "4:3",
        "overlay.aspect.threeTwo": "3:2",
        "overlay.aspect.sixteenNine": "16:9",
        "overlay.aspect.nineSixteen": "9:16",
        "common.apply": "应用",
        "overlay.accessibility.selectionCanvas": "截图选区",
        "overlay.accessibility.selectionValue": "宽 %d，高 %d",
        "tray.setting.includeCursor": "截图含鼠标",
        "tray.setting.captureAnimation": "截图启动动画",
        "tray.setting.pinShadow": "贴图阴影",
        "tray.detectWatermark": "检测水印",
        "tray.quickStart": "快速入门",
        "tray.letterToUsers": "给用户的信",
        "tray.legalNotices": "许可与声明",
        "tray.checkForUpdates": "检查更新",
        "tray.update.lastChecked": "上次：%@",
        "tray.update.lastChecked.never": "上次：未检查",
        "tray.about": "关于",
        "tray.update.available.title": "新版本可用",
        "tray.update.available.message": "PinboardShot v%@ 已准备好，可更新后重启。",
        "tray.update.install": "立即更新",
        "tray.update.later": "稍后",
        "menu.capture": "截图",
        "menu.quickSettings": "常用设置",
        "menu.manageSettings": "管理快捷键、历史与水印…",
        "menu.management": "管理",
        "menu.more": "更多",
        "menu.back": "返回",
        "menu.toolsAndHelp": "工具与帮助",
        "tray.pinboard.title": "你的贴图板",
        "tray.pinboard.subtitle": "截图将始终置顶，保持可见。",
        "tray.manageAndTools": "管理与工具",
        "menu.ready": "已就绪",
        "menu.permissionRequired": "需要屏幕录制权限",
        "menu.moreCapture": "更多截图",
        "menu.pinsWithCount": "贴图管理（%d）",
        "menu.showAllPins": "显示全部贴图",
        "menu.hideAllPins": "隐藏全部贴图",
        "menu.closeAllPins": "关闭全部贴图",
        "menu.restorePinInteraction": "恢复全部贴图交互",
        "menu.restorePinInteractionHelp": "让开启鼠标穿透的贴图重新接收点击",
        "menu.detectWatermark": "检测隐形水印…",
        "quality.native": "原生 Retina",
        "common.copy": "复制",
        "common.cancel": "取消",
        "common.add": "添加",
        "common.done": "完成",
        "scrollCapture.title": "滚动截图预览",
        "scrollCapture.selectionHint": "框选窗口内的可滚动区域 · Esc 取消",
        "scrollCapture.status.ready": "在所选区域内向下滚动，完成后点击“完成”。",
        "scrollCapture.status.capturing": "正在识别重叠内容并拼接…",
        "scrollCapture.status.unmatched": "暂时无法匹配当前画面，请放慢滚动并保留重叠内容。",
        "scrollCapture.status.limitReached": "已达到长截图临时存储上限，请点击“完成”。",
        "onboarding.title": "PinboardShot 已在菜单栏运行",
        "onboarding.message": "PinboardShot 不显示在 Dock 中。请在菜单栏找到取景框图标。\n\n默认不启用全局快捷键。可在设置中按需添加。\n\n截图需要屏幕录制权限。",
        "onboarding.requestPermission": "继续并请求权限",
        "onboarding.later": "稍后设置",
        "quickStart.title": "PinboardShot 快速入门",
        "quickStart.message": "从菜单栏使用截图与贴图功能。默认不启用全局快捷键，可在设置中按需添加。",
        "letterToUsers.title": "给用户的信",
        "letterToUsers.message": "谢谢你使用 PinboardShot。\n\n我做它，是希望截图、标注和贴图这类日常工具保持轻巧、安静，也足够可信。\n\nPinboardShot 会永久免费提供，不会改成订阅，也不会用付费墙锁住核心功能。\n\n它不会收集、上传或出售你的数据。截图、标注、历史和水印记录默认保存在本机；除软件更新外，只有当你明确配置远程 OCR 插件并主动使用 OCR 工具时，所选图片区域才会发送到你指定的服务。\n\n如果你遇到问题、觉得哪里别扭，或希望它支持某个小功能，随时欢迎在 GitHub Issues 反馈。我会认真看，也会尽力把它修好。",
        "legalNotices.title": "许可与声明",
        "legalNotices.message": "PinboardShot 随 App 附带以下开源许可与声明。",
        "legalNotices.noticesTab": "声明",
        "legalNotices.licenseTab": "许可",
        "legalNotices.missingTitle": "找不到许可与声明文件",
        "legalNotices.missingMessage": "请重新安装最新版本的 PinboardShot，或前往 GitHub 仓库查看 LICENSE 和 NOTICE。",
        "overlay.edit": "标注",
        "overlay.finishEditing": "完成标注",
        "overlay.dragToolbar": "拖动工具栏",
        "overlay.pin": "贴到屏幕",
        "overlay.pickColor": "取色",
        "overlay.pickColorTooltip": "取色并复制（%@）",
        "overlay.copyTooltip": "复制（回车）",
        "overlay.pinTooltip": "贴到屏幕（P）",
        "overlay.cancelTooltip": "取消（Esc）",
        "overlay.timeoutWarning": "即将自动取消；继续操作可保持截图",
        "colorPicker.format": "颜色格式",
        "colorPicker.format.hex": "HEX",
        "colorPicker.format.hexa": "HEX Alpha",
        "colorPicker.format.rgb": "RGB",
        "colorPicker.format.rgba": "RGBA",
        "colorPicker.format.hsl": "HSL",
        "colorPicker.format.swiftUI": "SwiftUI",
        "colorPicker.format.nsColor": "NSColor",
        "annotation.tool.mosaic": "马赛克",
        "annotation.tool.ocr": "OCR",
        "annotation.tool.ellipse": "椭圆",
        "annotation.tool.line": "直线",
        "annotation.tool.number": "步骤编号",
        "annotation.tool.redaction": "智能遮挡",
        "annotation.arrow.mode": "箭头绘制方式",
        "annotation.arrow.mode.straight": "普通箭头",
        "annotation.arrow.mode.freehand": "自由绘制箭头",
        "annotation.crop": "裁剪到所选矩形",
        "annotation.rotate": "顺时针旋转",
        "annotation.smartRedact": "智能脱敏",
        "annotation.smartRedactNone": "没有发现可自动遮挡的邮箱、电话、链接、二维码或人脸。",
        "composition.title": "截图拼板与美化",
        "composition.create": "创建拼板",
        "composition.chooseCaptures": "选择截图",
        "composition.titlePlaceholder": "可选标题",
        "composition.layout": "排列",
        "composition.layout.horizontal": "横向",
        "composition.layout.vertical": "纵向",
        "composition.layout.grid": "网格",
        "composition.background": "背景",
        "composition.background.transparent": "透明",
        "composition.background.light": "浅色",
        "composition.background.dark": "深色",
        "composition.background.blueGradient": "蓝紫渐变",
        "composition.shadow": "阴影",
        "composition.padding": "边距",
        "composition.cornerRadius": "圆角",
        "composition.empty": "请选择至少一张截图",
        "preferences.healthNeedsAttention": "需要处理",
        "preferences.screenCapturePermission": "截图权限",
        "preferences.permissionGranted": "屏幕录制权限已开启",
        "preferences.permissionMissing": "屏幕录制权限未开启",
        "preferences.permissionHelp": "macOS 将截图权限显示为“屏幕与系统音频录制”；PinboardShot 不录制音频，也不会上传截图。授权后若仍无法截图，请重新启动应用。",
        "preferences.copyDiagnostics": "复制诊断报告",
        "preferences.diagnosticsHelp": "报告只包含版本、权限、最近阶段和错误类型，不包含截图、文件路径或用户内容。",
        "annotation.ocr.pending": "正在识别…",
        "annotation.ocr.empty": "没找到可识别的文字",
        "annotation.ocr.failed": "文字识别失败，请重试",
        "ocr.preferences.tab": "OCR 插件",
        "ocr.preferences.providerSection": "文字识别方式",
        "ocr.preferences.provider": "OCR 提供方",
        "ocr.preferences.localProvider": "本机 OCR（Vision）",
        "ocr.preferences.localHelp": "默认在本机识别，不发送截图，也不需要网络。",
        "ocr.preferences.remoteHelp": "仅在你主动使用 OCR 标注工具时，将所选图片区域发送到配置的服务。历史索引和智能脱敏仍在本机运行。",
        "ocr.preferences.connectionSection": "插件连接",
        "ocr.preferences.pluginUnavailable": "已选择的插件不可用。请重新载入插件或切回本机 OCR。",
        "ocr.preferences.baseURL": "Base URL，例如 https://api.example.com/v1",
        "ocr.preferences.model": "模型名称",
        "ocr.preferences.apiKey": "API Key",
        "ocr.preferences.apiKeySavedPlaceholder": "API Key 已存入钥匙串；留空可保留",
        "ocr.preferences.keychainHelp": "API Key 仅保存在 macOS 钥匙串中，并在发出请求时注入鉴权头。Base URL 和模型保存在偏好设置中。",
        "ocr.preferences.removeAPIKey": "移除 API Key",
        "ocr.preferences.pluginsSection": "开发与管理",
        "ocr.preferences.openPluginsFolder": "打开插件文件夹",
        "ocr.preferences.reloadPlugins": "重新载入",
        "ocr.preferences.pluginsHelp": "将 OCR 插件 manifest（JSON）放入此文件夹。插件只能声明相对请求路径、JSON 请求模板和响应文字路径。",
        "ocr.preferences.loadErrors": "%d 个插件未能载入；将指针停留在此处查看原因。",
        "ocr.preferences.saved": "OCR 设置已保存。",
        "ocr.preferences.apiKeyRemoved": "API Key 已从钥匙串移除。",
        "ocr.error.invalidManifest": "OCR 插件无效：%@",
        "ocr.error.pluginsDirectoryUnavailable": "无法访问 OCR 插件文件夹。",
        "ocr.error.pluginNotFound": "已选择的 OCR 插件不可用。",
        "ocr.error.invalidBaseURL": "请输入有效的 OCR 服务 Base URL。",
        "ocr.error.insecureBaseURL": "OCR 服务必须使用 HTTPS；只有 localhost 可以使用 HTTP。",
        "ocr.error.modelRequired": "请输入该 OCR 插件需要的模型名称。",
        "ocr.error.apiKeyRequired": "请输入该 OCR 插件需要的 API Key。",
        "ocr.error.invalidAPIKey": "API Key 不能包含换行符。",
        "ocr.error.imageTooLarge": "所选 OCR 图片超过 20 MB 请求上限。",
        "ocr.error.invalidResponse": "OCR 服务返回了无法解析的响应。",
        "ocr.error.responseTooLarge": "OCR 服务响应超过 5 MB 上限。",
        "ocr.error.httpStatus": "OCR 服务返回 HTTP %d。",
        "ocr.error.crossOriginRedirect": "OCR 服务尝试重定向到其他来源，已阻止发送鉴权信息。",
        "ocr.error.keychain": "钥匙串操作失败（%d）。",
        "preferences.shortcutUnsafe": "需要功能键或 ⌘、⌥、⌃ 修饰键",
        "preferences.trayIcon.solCrafted": "GPT-5.6 Sol 星芒",
        "pin.zoomIn": "放大",
        "pin.zoomOut": "缩小",
        "pin.restoreInitialState": "恢复初始状态",
        "pin.save": "保存图片…",
        "pin.enableMousePassthrough": "开启鼠标穿透",
        "pin.disableMousePassthrough": "关闭鼠标穿透",
        "pin.saveFailedTitle": "无法保存图片",
        "pin.saveFailedMessage": "图片没有保存：%@",
        "pin.opacityUp": "提高不透明度",
        "pin.opacityDown": "降低不透明度",
        "pin.lockPosition": "锁定位置",
        "pin.unlockPosition": "解锁位置",
        "pin.currentSpaceOnly": "仅当前桌面空间",
        "pin.allSpaces": "所有桌面空间",
        "pin.currentApplicationOnly": "仅当前应用",
        "pin.allApplications": "所有应用",
        "pin.enableAutoFade": "鼠标移入时暂隐",
        "pin.disableAutoFade": "关闭鼠标移入暂隐",
        "pin.accessibility.image": "贴屏图片",
        "pinWorkspace.preferencesTab": "贴图工作区",
        "pinWorkspace.saveCurrent": "保存当前贴图为工作区…",
        "pinWorkspace.savePromptTitle": "保存贴图工作区",
        "pinWorkspace.savePromptMessage": "保存当前全部贴图及其位置、尺寸和交互状态。",
        "pinWorkspace.save": "保存工作区",
        "pinWorkspace.namePlaceholder": "工作区名称",
        "pinWorkspace.savedTitle": "工作区已保存",
        "pinWorkspace.savedMessage": "“%@”已保存（%d 张贴图）。",
        "pinWorkspace.errorTitle": "无法完成贴图工作区操作",
        "pinWorkspace.error.invalidName": "请输入 1–80 个字符的工作区名称。",
        "pinWorkspace.error.noPins": "当前没有可保存的贴图。",
        "pinWorkspace.error.imageEncoding": "至少有一张贴图无法编码，工作区没有保存。",
        "pinWorkspace.error.unavailable": "贴图工作区不存在、已损坏或暂时无法访问。",
        "pinWorkspace.error.unsupportedSchema": "此贴图工作区来自不受支持的版本。",
        "pinWorkspace.error.noRestorablePins": "工作区内没有可恢复的有效图片。",
        "pinWorkspace.saveSection": "保存当前贴图",
        "pinWorkspace.saveHelp": "手动保存当前全部贴图。默认不会在启动时自动恢复。",
        "pinWorkspace.savedSection": "已保存的工作区",
        "pinWorkspace.emptyTitle": "还没有贴图工作区",
        "pinWorkspace.emptyMessage": "摆放好贴图后，在上方输入名称并保存。",
        "pinWorkspace.itemSummary": "%d 张贴图 · %@",
        "pinWorkspace.restore": "恢复",
        "pinWorkspace.delete": "删除工作区",
        "pinWorkspace.loadWarnings": "%d 个工作区无法读取；其他工作区仍可正常使用。",
        "pinWorkspace.privacyHelp": "工作区图片和状态只保存在本机。恢复会添加贴图，不会关闭当前贴图；删除工作区也不会关闭已显示的贴图。",
        "pinWorkspace.deleteTitle": "删除贴图工作区？",
        "pinWorkspace.deleteMessage": "将删除“%@”保存的图片和状态。当前已显示的贴图不受影响。",
        "pinWorkspace.deletedMessage": "已删除“%@”。",
        "pinWorkspace.restoredMessage": "已恢复“%@”（%d 张贴图）。",
        "pinWorkspace.restoredWithWarnings": "已恢复 %d 张贴图；跳过 %d 张缺失图片；移除了 %d 个失效的 App 限制。",
        "error.permissionDenied": "需要开启屏幕录制权限后才能截图。",
        "error.captureBusy": "上一项截图仍在处理中，请完成或取消后重试。",
        "error.captureTimedOut": "系统截图服务响应超时，请重试。",
        "error.displayUnavailable": "没有找到可截图的屏幕。",
        "error.windowUnavailable": "光标下没有可截图的窗口。",
        "error.clipboardHasNoImage": "剪贴板中没有图片。",
        "error.lastRegionUnavailable": "还没有可重复的截图区域，请先完成一次区域截图。",
        "error.imageEncodingFailed": "图片编码失败。",
        "error.imageScalingFailed": "无法生成所选清晰度的截图，请降低输出级别后重试。",
        "error.invalidSelection": "截图选区超出了屏幕范围。",
        "error.emptyCaptureFrame": "本次截图被判定为空白帧，剪贴板没有更新，仍保留上一次内容。请重新选择包含可见内容的区域。",
        "error.scrollTargetUnavailable": "选区中心没有找到可持续捕获的窗口。请重新框选窗口内的滚动区域。",
        "error.scrollCaptureNoMovement": "没有检测到可拼接的滚动内容。请开始后向下滚动，再点击完成。",
        "error.ocrNoText": "没有在选区内识别到可复制的文字。",
        "watermark.preferences.tab": "水印",
        "watermark.preferences.section": "隐形取证水印",
        "watermark.preferences.enabled": "为新截图嵌入隐形水印",
        "watermark.preferences.enabledHelp": "启用后，截图会写入不可见的随机标识；不会上传图片或水印记录。小于 320 × 200 的截图无法嵌入。",
        "watermark.preferences.details": "本地记录信息",
        "watermark.preferences.project": "项目或工作区",
        "watermark.preferences.recipient": "接收方或分发对象",
        "watermark.preferences.customText": "自定义文案",
        "watermark.preferences.privacyPreview": "图片像素中只嵌入协议版本、随机截图 ID 和校验码。以上文字仅保存在本机，并使用钥匙串密钥签名。",
        "watermark.preferences.localRecords": "本地水印记录",
        "preferences.selectionToolbarIcons": "选区工具栏图标",
        "preferences.selectionToolbarIconsReset": "还原默认图标",
        "preferences.selectionToolbarIconsHelp": "直接选择预设图标；重置后使用默认图标。改动会在下一次框选时生效。",
        "preferences.toolbar": "工具栏",
        "preferences.selectionToolbar.configuration": "显示与顺序",
        "preferences.selectionToolbar.annotationTools": "标注工具组",
        "preferences.selectionToolbar.autoSort": "根据使用频次自动排序",
        "preferences.selectionToolbar.autoSortHelp": "开启后，下次框选时已显示工具会按本机使用次数从高到低排列；相同频次沿用手动顺序，不会在当前操作中跳动。只记录工具次数，不记录截图内容。",
        "preferences.selectionToolbar.visibilityHelp": "默认显示标注工具组、复制、贴图和取消。隐藏的工具仍可随时在这里恢复；复制和取消始终保留。",
        "preferences.selectionToolbar.required": "必需",
        "preferences.selectionToolbar.moveUp": "提高优先级",
        "preferences.selectionToolbar.moveDown": "降低优先级",
        "preferences.selectionToolbar.reset": "恢复默认工具栏",
        "watermark.preferences.recordCount": "已保存 %d 条记录",
        "watermark.preferences.clearRecords": "清空水印记录",
        "watermark.preferences.clearConfirmTitle": "清空全部水印记录？",
        "watermark.preferences.clearConfirmMessage": "此操作不会修改已导出的图片，但之后只能检测到图片中的随机 ID，无法恢复项目、接收方和自定义文案。",
        "watermark.preferences.clearFailed": "无法清空水印记录：%@",
        "watermark.detect.panelMessage": "选择需要检测的 PNG 或 JPEG 图片。",
        "watermark.detect.notFoundTitle": "未检测到 PinboardShot 水印",
        "watermark.detect.notFoundMessage": "图片可能没有水印，或水印已因大幅裁剪、编辑、压缩或再截图而无法恢复。",
        "watermark.detect.recordMissingTitle": "检测到水印，但本机没有对应记录",
        "watermark.detect.recordMissingMessage": "截图 ID：%@\n\n记录可能已被清除，或图片来自另一台设备。",
        "watermark.detect.invalidTitle": "水印记录签名无效",
        "watermark.detect.invalidMessage": "截图 ID：%@\n\n本地记录可能已被修改，不能确认其中的信息。",
        "watermark.detect.verifiedTitle": "已验证 PinboardShot 隐形水印",
        "watermark.detect.emptyValue": "未填写",
        "watermark.detect.id": "截图 ID：%@",
        "watermark.detect.createdAt": "创建时间：%@",
        "watermark.detect.project": "项目：%@",
        "watermark.detect.recipient": "接收方：%@",
        "watermark.detect.customText": "自定义文案：%@",
        "watermark.detect.exactImage": "完整性：与本机保存时的 PNG 完全一致",
        "watermark.detect.transformedImage": "完整性：水印有效，但图片字节已变化，可能经过压缩、缩放、裁剪或重新编码",
        "watermark.error.imageTooSmall": "截图尺寸过小，隐形水印至少需要 320 × 200 像素。",
        "watermark.error.imageConversionFailed": "无法生成或检测隐形水印。",
        "watermark.error.keyUnavailable": "无法访问隐形水印签名密钥，请检查钥匙串访问后重试。",
        "annotation.clear": "清除全部",
        "annotation.color": "颜色",
        "annotation.copy": "复制结果",
        "annotation.pin": "贴到屏幕",
        "annotation.redo": "重做",
        "annotation.title": "图片标注",
        "annotation.undo": "撤销",
        "annotation.width": "粗细",
        "common.ok": "确定",
        "hotkey.failure.message": "这些组合可能已被系统或其他应用占用：\n\n%@\n\n请在设置中更换组合。",
        "hotkey.failure.title": "部分全局快捷键注册失败",
        "launch.registeredNeedsApproval": "已经登记，但需要在系统设置的“登录项”中批准。",
        "launch.requiresApproval": "需要在系统设置的“登录项”中批准 PinboardShot。",
        "launch.updateFailed": "更新开机自启失败：%@",
        "menu.hotkeyFailures": "%d 项快捷键注册失败",
        "menu.permissionMissing": "屏幕录制权限未开启，点击授权",
        "menu.quit": "退出 PinboardShot",
        "overlay.hint": "拖动选择区域 · 双击复制 · Esc 取消",
        "permission.openSettings": "打开系统设置",
        "pin.close": "关闭贴图",
        "pin.copy": "复制图片",
        "preferences.8kWarning": "8K 会显著增加内存占用、剪贴板体积和 PNG 编码时间。",
        "preferences.addShortcut": "添加快捷键",
        "preferences.allowDarkCaptures": "允许均匀纯黑或深色截图",
        "preferences.allowDarkCapturesHelp": "仅在需要截取纯黑内容时启用；开启后异常黑帧保护会降低。",
        "preferences.automaticallyCheckForUpdates": "自动检查更新",
        "preferences.capture": "截图",
        "preferences.captureAnimation": "截图开始时显示轻量动画",
        "preferences.clearOnQuit": "退出应用时清空截图历史",
        "preferences.deleteShortcut": "删除这条快捷键",
        "preferences.general": "偏好",
        "preferences.history": "历史",
        "preferences.includeCursor": "全屏和区域截图包含鼠标指针",
        "preferences.keyCombination": "按键组合",
        "preferences.language": "界面语言",
        "preferences.languageSection": "语言",
        "preferences.launch": "启动",
        "preferences.launchAtLogin": "登录时自动启动 PinboardShot",
        "preferences.localOnly": "PinboardShot 只在本机保存截图，仅软件更新会访问网络，不包含分析服务。",
        "preferences.openLoginSettings": "打开登录项设置",
        "preferences.outputQuality": "输出清晰度",
        "preferences.pinHelp": "拖动贴图移动；拖动边缘或双指捏合缩放；右键可恢复初始状态或执行其他操作。",
        "preferences.pinOperations": "贴图操作",
        "preferences.pinShadow": "贴图显示阴影",
        "preferences.pinToScreen": "贴到屏幕",
        "preferences.pressShortcut": "请按组合键…",
        "preferences.privacy": "隐私",
        "preferences.qualityHelp": "标准级别会保持宽高比并只放大、不压缩原生像素。",
        "preferences.recordHelp": "点击按键组合，然后直接按下你想使用的快捷键。",
        "preferences.restoreShortcuts": "清除所有快捷键",
        "preferences.shortcutConflict": "该组合无效或已经被其他快捷键使用。",
        "preferences.shortcutHelp": "默认不启用快捷键。每个动作可以绑定多组快捷键；普通字母组合必须包含 ⌘、⌥ 或 ⌃。",
        "preferences.shortcuts": "快捷键",
        "preferences.trayIcon": "菜单栏图标",
        "preferences.trayIcon.color": "彩色",
        "preferences.trayIcon.monochrome": "单色",
        "preferences.trayIconHelp": "选择后立即生效。单色图标自动适配浅色与深色菜单栏；动态图标会持续变化，开启“减弱动态效果”时保持静止。",
        "preferences.triggerAction": "触发动作",
        "preferences.updateCheckFrequency": "检查周期",
        "preferences.updateCheckHelp": "开启后，PinboardShot 只会按所选周期访问签名更新清单，不会强制安装。",
        "preferences.updateFrequency.daily": "每天",
        "preferences.updateFrequency.everySixHours": "每 6 小时",
        "preferences.updateFrequency.everyThreeDays": "每 3 天",
        "preferences.updateFrequency.everyTwelveHours": "每 12 小时",
        "preferences.updateFrequency.hourly": "每小时",
        "preferences.updateFrequency.weekly": "每周",
        "preferences.updates": "软件更新",
        "preferences.windowTitle": "PinboardShot 设置",
        "preferences.search": "搜索",
        "scrollCapture.status.revisited": "正在浏览已捕获区域，继续滚动即可无缝接回。",
        "comparison.title": "视觉对比",
        "comparison.mode": "对比方式",
        "comparison.mode.sideBySide": "并排",
        "comparison.mode.overlay": "差异叠加",
        "comparison.mode.blend": "透明混合",
        "comparison.swap": "交换 A 与 B",
        "comparison.opacity": "B 图不透明度",
        "comparison.canvas": "图片对比画布",
        "comparison.imageAccessibility": "%@ 图，%d × %d 像素",
        "comparison.export": "导出结果…",
        "comparison.exportHelp": "把当前对比方式导出为图片",
        "comparison.exportErrorTitle": "无法导出对比结果",
        "comparison.exportErrorMessage": "无法导出对比结果：%@",
        "pin.compare.needsTwoPins": "至少需要两张贴图才能对比",
        "pin.compare.discoveryHint": "现在有两张贴图了。右键一张设为基准 A，再右键另一张开始视觉对比。",
        "pin.compare.setReference": "设为对比基准 A",
        "pin.compare.cancelReference": "取消对比基准",
        "pin.compare.withReference": "与基准 A 对比",
        "pin.compare.sideBySide": "并排对比",
        "pin.compare.overlay": "差异叠加",
        "pin.compare.blend": "透明混合",
        "pin.metadata.edit": "编辑备注与标签…",
        "pin.metadata.accessibility.empty": "没有备注或标签",
        "pin.metadata.accessibility.summary": "%d 条备注，%d 个标签",
        "pin.metadata.editor.title": "贴图备注与标签",
        "pin.metadata.editor.note": "备注",
        "pin.metadata.editor.tags": "标签",
        "pin.metadata.editor.tagsPlaceholder": "设计, 待确认, 参考",
        "pin.metadata.editor.tagsHelp": "使用逗号或换行分隔标签；最多 12 个，每个不超过 32 个字符。",
        "pin.metadata.editor.validationError": "无法保存：%@",
        "preferences.pinSessionRecovery.title": "重新启动后恢复未保存的贴图",
        "preferences.pinSessionRecovery.help": "关闭时不会保存临时会话；开启后只在本机保留最多 24 小时的恢复副本。",
        "history.searchHelp": "搜索 OCR 文字、图片尺寸或来源应用。",
        "history.clearByTime": "按时间清理",
        "history.cleanupOneDay": "1 天前",
        "history.cleanupSevenDays": "7 天前",
        "history.cleanupThirtyDays": "30 天前",
        "history.cleanupNinetyDays": "90 天前",
        "history.cleanupAll": "全部",
        "history.cleanupHelp": "先预览截图数量和可释放空间，确认后再删除。",
        "history.clearHistory": "清理截图",
        "history.clearHistoryTitle": "截图历史清理结果",
        "history.clearHistoryMessage": "将删除 %d 张截图，预计释放 %@。此操作无法撤销。",
        "history.clearHistoryNone": "没有符合条件的截图可清理（%d 张）。",
        "history.clearHistoryDone": "已清理 %d 张截图。",
        "history.clearHistoryFailed": "清理失败：%@",
        "history.storageAndPrivacy": "存储与隐私",
        "history.refreshStorage": "刷新用量",
        "history.storageHistory": "截图历史：%d 张",
        "history.storageHistoryImages": "图片：%@",
        "history.storageHistoryIndex": "索引：%@",
        "history.clearOCRIndex": "清除 OCR 索引",
        "history.clearOCRIndexHelp": "只清除识别文字和索引状态，不删除截图。",
        "history.clearOCRIndexMessage": "将清除全部历史截图的识别文字。原图会保留，之后可按需重新识别。",
        "history.applicationExclusions": "不保存以下应用的截图历史",
        "history.addExcludedApplication": "添加应用…",
        "history.removeExcludedApplication": "移除排除应用",
        "history.noExcludedApplications": "尚未排除任何应用。",
        "history.chooseApplication": "选择一个不写入截图历史的应用。",
        "history.exclusionNoBundle": "所选应用没有可识别的 Bundle ID。",
        "history.exclusionUnknownSelf": "无法识别 PinboardShot 的 Bundle ID，请稍后重试。",
        "history.exclusionSelf": "不能将 PinboardShot 自身加入排除列表。",
        "history.exclusionFailClosedHelp": "排除列表非空时，如果无法识别截图来源应用，该截图不会写入历史；复制和贴图仍可正常使用。",
        "history.status.notIndexed": "未建立 OCR 索引",
        "history.status.pending": "正在识别文字…",
        "history.status.indexed": "已建立 OCR 索引",
        "history.status.empty": "未识别到文字",
        "history.status.failed": "文字识别失败",
        "history.copyRecognizedText": "复制识别文字",
        "history.viewDetails": "查看截图详情",
        "history.reindex": "重新识别文字",
        "history.dimension": "%d × %d 像素",
        "history.imageMissing": "原始截图文件已不存在。",
        "history.ocrTextTitle": "识别文字",
        "history.noRecognizedText": "这张截图没有可用的识别文字。",
        "pinWorkspace.sort": "排序",
        "pinWorkspace.sortUpdated": "最近更新",
        "pinWorkspace.sortName": "名称",
        "pinWorkspace.sortRestored": "最近恢复",
        "pinWorkspace.notRestored": "尚未恢复",
        "pinWorkspace.recentSummary": "上次恢复：%@ · %d 条备注 · 标签：%@",
        "pinWorkspace.moreActions": "更多工作区操作",
        "pinWorkspace.restoreAgain": "再次恢复",
        "pinWorkspace.rename": "重命名…",
        "pinWorkspace.renameTitle": "重命名贴图工作区",
        "pinWorkspace.renamedMessage": "已重命名为“%@”。",
        "pinWorkspace.duplicate": "创建副本…",
        "pinWorkspace.duplicateTitle": "创建工作区副本",
        "pinWorkspace.duplicateHelp": "为“%@”创建完整副本，包括图片、位置、备注与标签。",
        "pinWorkspace.duplicatePlaceholder": "副本名称（留空自动生成）",
        "pinWorkspace.duplicatedMessage": "已创建“%@”副本（%d 张贴图）。",
        "pinWorkspace.exportImages": "导出图片集…",
        "pinWorkspace.exportPDF": "导出 PDF…",
        "pinWorkspace.exportMarkdown": "导出 Markdown…",
        "pinWorkspace.export.chooseDirectory": "选择工作区导出位置",
        "pinWorkspace.export.action": "导出",
        "pinWorkspace.exportNoFile": "已取消导出。",
        "pinWorkspace.exportSuccess": "已导出到“%@”（%d 张，跳过 %d 张）。",
        "pinWorkspace.export.error.invalidDestination": "所选导出位置不可用。",
        "pinWorkspace.export.error.noExportablePins": "工作区中没有可导出的有效图片。",
        "pinWorkspace.export.error.pdfCreationFailed": "无法创建 PDF。",
        "pinWorkspace.storageSummary": "贴图工作区：%lld 字节",
        "pinWorkspace.storageWorkspaceCount": "工作区：%d 个",
        "pinWorkspace.storageRecovery": "会话恢复：%lld 字节",
        "pinWorkspace.storagePins": "已保存贴图：%d 张"
    ]
}

@MainActor
final class LocalizationStore: ObservableObject {
    @Published private(set) var language: AppLanguage
    var onLanguageChanged: (() -> Void)?

    init(defaults: UserDefaults = .standard) {
        language = AppLanguage.current(defaults: defaults)
    }

    func setLanguage(_ language: AppLanguage) {
        guard self.language != language else { return }
        UserDefaults.standard.set(language.rawValue, forKey: AppLanguage.userDefaultsKey)
        self.language = language
        onLanguageChanged?()
    }
}
